server:
  port: 8090
spring:
  application:
    name: eshop-zull
eureka: 
  client: 
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://eureka2001.hmc.com:8081/eureka/,http://eureka2002.hmc.com:8082/eureka/,http://eureka2003.hmc.com:8083/eureka/ # 集群
# 构建路由地址
zuul:
  routes:
    # 这里可以自定义
    api-usercenter:
      # 匹配的路由规则
      path: /user/**
      # 路由的目标服务名
      serviceId: eshop-usercenter
    api-order:
      # 匹配的路由规则
      path: /order/**
      # 路由的目标服务名
      serviceId: eshop-order
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #断路器超时时间，默认1000ms

feign:
  hystrix:
    enabled: true          
  client:
    config:
      default:
        connectTimeout: 5000 # feign 的超时设置
        readTimeout: 5000    