spring:
  application:
    name: eshop-eureka-ha
server:
  port: 8083
  
eureka: 
  client: 
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka2001.hmc.com:8081/eureka/,http://eureka2002.hmc.com:8082/eureka/ # 集群
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址